Repository KyoPak/ios-wanted-GyroData, pull requests merged in 2023-02, with the labels that each got.

#16 11 unit test transactionservice 단위테스트
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Domain/Entities/MeasureData.swift
  GyroData/Source/Domain/Entities/Sensor.swift
  GyroDataTests/Common/Dummy/MeasureDataDummy.swift
  GyroDataTests/Common/Mock/CoreDataManagerMock.swift
  GyroDataTests/Common/Mock/FileSystemManagerMock.swift
  GyroDataTests/Common/Stub/CoreDataManagerStub.swift
  GyroDataTests/Common/Stub/FileSystemManagerStub.swift
  GyroDataTests/CoreDataManagerTests/CoreDataManagerTests.swift
  GyroDataTests/FileSystemManagerTests/FileSystemManagerTests.swift
  GyroDataTests/TransactionServiceTests/TransactionServiceTests.swift
Labels: 🔬test

#21 15 feature 센서 값 측정을 담당하는 객체 생성
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Domain/SensorMeasureService.swift
Labels: ⚙️ feature

#27 graphView 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Domain/Entities/MeasureData.swift
  GyroData/Source/Presentation/Common/Views/GraphView.swift
Labels: ⚙️ feature

#28 13 feature measureviewmodel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Domain/Protocol/MeasureServiceDelegate.swift
  GyroData/Source/Domain/SensorMeasureService.swift
  GyroData/Source/Presentation/Common/Views/GraphView.swift
  GyroData/Source/Presentation/MeasureScene/MeasureViewModel.swift
  GyroData/Source/Presentation/Protocol/MeasureViewDelegate.swift
Labels: ⚙️ feature

#29 13 feature measureviewmodel 구현
  GyroData/Source/Data/CoreData/SensorData.xcdatamodeld/SensorData.xcdatamodel/contents
  GyroData/Source/Domain/SensorMeasureService.swift
  GyroData/Source/Presentation/Common/Views/GraphView.swift
  GyroData/Source/Presentation/MeasureScene/MeasureViewModel.swift
Labels: ⚒️ refactor

#30 22 feature detailviewmodel 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Presentation/DataListScene/DataListViewController.swift
  GyroData/Source/Presentation/DataListScene/DataListViewModel.swift
  GyroData/Source/Presentation/ReviewScene/DetailViewController.swift
  GyroData/Source/Presentation/ReviewScene/DetailViewModel.swift
Labels: ⚙️ feature

#32 refactor : DataListViewModel에서 ViewController의 액션을 하나의 메서드에서 처리하도록 변경
  GyroData/Source/Presentation/DataListScene/DataListViewController.swift
  GyroData/Source/Presentation/DataListScene/DataListViewModel.swift
Labels: ⚙️ feature, ⚒️ refactor

#38 35 feature 재사용 가능한 alert controller 생성
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Common/Builder/AlertBuilder.swift
  GyroData/Source/Common/Builder/ErrorAlertBuilder.swift
  GyroData/Source/Common/Director/AlertDirector.swift
  GyroData/Source/Common/Error/FileSystemError.swift
  GyroData/Source/Domain/TransactionService.swift
  GyroData/Source/Presentation/DataListScene/DataListViewController.swift
  GyroData/Source/Presentation/DataListScene/DataListViewModel.swift
Labels: ⚙️ feature

#42 24 feature playviewmodel, playviewcontroller 구현
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Presentation/Common/Views/GraphView.swift
  GyroData/Source/Presentation/DataListScene/DataListViewController.swift
  GyroData/Source/Presentation/DataListScene/DataListViewModel.swift
  GyroData/Source/Presentation/MeasureScene/MeasureViewController.swift
  GyroData/Source/Presentation/PlayScene/PlayViewController.swift
  GyroData/Source/Presentation/PlayScene/PlayViewModel.swift
  GyroData/Source/Presentation/Protocol/GraphViewPlayDelegate.swift
  GyroData/Source/Presentation/Protocol/PlayViewDelegate.swift
Labels: ⚙️ feature

#43 refactor : activityIndicator 위치 수정
  GyroData/Source/Presentation/MeasureScene/MeasureViewController.swift
  GyroData/Source/Presentation/PlayScene/PlayViewController.swift
  GyroData/Source/Presentation/PlayScene/PlayViewModel.swift
Labels: ⚒️ refactor

#45 feat : DateFormatter Extension하여 양식에 맞는 String으로 변경하는 기능 추가
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Common/Extension/DateFormatter+Extension.swift
  GyroData/Source/Presentation/DataListScene/MeasureDataCell.swift
  GyroData/Source/Presentation/PlayScene/PlayViewController.swift
  GyroData/Source/Presentation/ReviewScene/DetailViewController.swift
Labels: ⚙️ feature

#46 Coredata fetch refactor, scroll Pagination
  GyroData.xcodeproj/project.pbxproj
  GyroData/Source/Application/SceneDelegate.swift
  GyroData/Source/Domain/TransactionService.swift
  GyroData/Source/Presentation/DataListScene/DataListViewController.swift
  GyroData/Source/Presentation/DataListScene/DataListViewModel.swift
Labels: ⚙️ feature, ⚒️ refactor
